[package]
name = "glasswyrmd"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Glasswyrm X11 protocol server process"
publish = false

[dependencies]
glasswyrm-core = { path = "../glasswyrm-core" }
glasswyrm-x11 = { path = "../glasswyrm-x11" }

[lib]
path = "src/lib.rs"

[[bin]]
name = "glasswyrmd"
path = "src/main.rs"

[lints]
workspace = true
