#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u8)]
pub enum CoreOpcode {
    CreateWindow = 1,
    ChangeWindowAttributes = 2,
    GetWindowAttributes = 3,
    DestroyWindow = 4,
    MapWindow = 8,
    MapSubwindows = 9,
    UnmapWindow = 10,
    UnmapSubwindows = 11,
    ConfigureWindow = 12,
    GetGeometry = 14,
    QueryTree = 15,
    InternAtom = 16,
    GetAtomName = 17,
    ChangeProperty = 18,
    DeleteProperty = 19,
    GetProperty = 20,
    ListProperties = 21,
    SetSelectionOwner = 22,
    GetSelectionOwner = 23,
    ConvertSelection = 24,
    SendEvent = 25,
    GrabPointer = 26,
    UngrabPointer = 27,
    GrabButton = 28,
    ChangeActivePointerGrab = 30,
    GrabKeyboard = 31,
    UngrabKeyboard = 32,
    AllowEvents = 35,
    QueryPointer = 38,
    TranslateCoordinates = 40,
    WarpPointer = 41,
    SetInputFocus = 42,
    GetInputFocus = 43,
    QueryKeymap = 44,
    OpenFont = 45,
    CloseFont = 46,
    QueryFont = 47,
    QueryTextExtents = 48,
    ListFonts = 49,
    CreatePixmap = 53,
    FreePixmap = 54,
    CreateGc = 55,
    ChangeGc = 56,
    FreeGc = 60,
    ClearArea = 61,
    CopyArea = 62,
    PolyLine = 65,
    PolySegment = 66,
    FillPoly = 69,
    PolyFillRectangle = 70,
    PolyFillArc = 71,
    PutImage = 72,
    PolyText8 = 74,
    ImageText8 = 76,
    CreateColormap = 78,
    FreeColormap = 79,
    InstallColormap = 81,
    UninstallColormap = 82,
    ListInstalledColormaps = 83,
    AllocColor = 84,
    AllocNamedColor = 85,
    FreeColors = 88,
    QueryColors = 91,
    LookupColor = 92,
    CreateCursor = 93,
    CreateGlyphCursor = 94,
    FreeCursor = 95,
    RecolorCursor = 96,
    QueryBestSize = 97,
    QueryExtension = 98,
    ListExtensions = 99,
    GetKeyboardMapping = 101,
    ChangeKeyboardControl = 102,
    GetKeyboardControl = 103,
    Bell = 104,
    ForceScreenSaver = 115,
    GetPointerMapping = 117,
    GetModifierMapping = 119,
    NoOperation = 127,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u8)]
pub enum CoreErrorCode {
    BadRequest = 1,
    BadValue = 2,
    BadWindow = 3,
    BadPixmap = 4,
    BadAtom = 5,
    BadCursor = 6,
    BadFont = 7,
    BadMatch = 8,
    BadDrawable = 9,
    BadAccess = 10,
    BadAlloc = 11,
    BadColormap = 12,
    BadGContext = 13,
    BadIdChoice = 14,
    BadName = 15,
    BadLength = 16,
    BadImplementation = 17,
}

#[must_use]
pub const fn wire_sequence(sequence: u64) -> u16 {
    (sequence & 0xffff) as u16
}
