#ifndef GLASSWYRM_IPC_CONTRACTS_H
#define GLASSWYRM_IPC_CONTRACTS_H

#include <glasswyrm/ipc/types.h>

#define GWIPC_DEFAULT_MAXIMUM_PAYLOAD UINT32_C(65536)
#define GWIPC_DEFAULT_MAXIMUM_FDS UINT16_C(4)
#define GWIPC_DEFAULT_MAXIMUM_QUEUED_BYTES UINT32_C(1048576)
#define GWIPC_DEFAULT_MAXIMUM_QUEUED_MESSAGES UINT16_C(256)
#define GWIPC_HARD_MAXIMUM_PAYLOAD UINT32_C(1048576)
#define GWIPC_HARD_MAXIMUM_FDS UINT16_C(16)
#define GWIPC_HARD_MAXIMUM_QUEUED_BYTES UINT32_C(16777216)

#endif
