#include "ipc/wire/input_contract.hpp"
#include "ipc/wire/byte_reader.hpp"
#include "ipc/wire/byte_writer.hpp"
namespace gw::ipc::wire {
std::vector<std::uint8_t> encode(const SyntheticMotion&v){ByteWriter w;w.u64(v.input_id);w.u32(v.time_ms);w.i32(v.root_x);w.i32(v.root_y);w.u32(v.flags);return std::move(w).take();}
CodecStatus decode(std::span<const std::uint8_t>b,SyntheticMotion&v){ByteReader r(b);SyntheticMotion x;if(!r.u64(x.input_id)||!r.u32(x.time_ms)||!r.i32(x.root_x)||!r.i32(x.root_y)||!r.u32(x.flags))return CodecStatus::Truncated;if(!r.done())return CodecStatus::TrailingData;if(!x.input_id||!x.time_ms||x.flags)return CodecStatus::InvalidValue;v=x;return CodecStatus::Ok;}
std::vector<std::uint8_t> encode(const SyntheticButton&v){ByteWriter w;w.u64(v.input_id);w.u32(v.time_ms);w.u8(v.button);w.u8(v.pressed);w.u16(v.reserved16);w.u32(v.flags);return std::move(w).take();}
CodecStatus decode(std::span<const std::uint8_t>b,SyntheticButton&v){ByteReader r(b);SyntheticButton x;if(!r.u64(x.input_id)||!r.u32(x.time_ms)||!r.u8(x.button)||!r.u8(x.pressed)||!r.u16(x.reserved16)||!r.u32(x.flags))return CodecStatus::Truncated;if(!r.done())return CodecStatus::TrailingData;if(!x.input_id||!x.time_ms||x.button<1||x.button>5||x.pressed>1||x.reserved16||x.flags)return CodecStatus::InvalidValue;v=x;return CodecStatus::Ok;}
std::vector<std::uint8_t> encode(const SyntheticKey&v){ByteWriter w;w.u64(v.input_id);w.u32(v.time_ms);w.u8(v.keycode);w.u8(v.pressed);w.u16(v.reserved16);w.u32(v.flags);return std::move(w).take();}
CodecStatus decode(std::span<const std::uint8_t>b,SyntheticKey&v){ByteReader r(b);SyntheticKey x;if(!r.u64(x.input_id)||!r.u32(x.time_ms)||!r.u8(x.keycode)||!r.u8(x.pressed)||!r.u16(x.reserved16)||!r.u32(x.flags))return CodecStatus::Truncated;if(!r.done())return CodecStatus::TrailingData;if(!x.input_id||!x.time_ms||x.keycode<8||x.pressed>1||x.reserved16||x.flags)return CodecStatus::InvalidValue;v=x;return CodecStatus::Ok;}
std::vector<std::uint8_t> encode(const SyntheticBarrier&v){ByteWriter w;w.u64(v.input_id);w.u32(v.flags);return std::move(w).take();}
CodecStatus decode(std::span<const std::uint8_t>b,SyntheticBarrier&v){ByteReader r(b);SyntheticBarrier x;if(!r.u64(x.input_id)||!r.u32(x.flags))return CodecStatus::Truncated;if(!r.done())return CodecStatus::TrailingData;if(!x.input_id||x.flags)return CodecStatus::InvalidValue;v=x;return CodecStatus::Ok;}
std::vector<std::uint8_t> encode(const SyntheticInputAcknowledged&v){ByteWriter w;w.u64(v.input_id);w.u32(v.time_ms);w.u16(static_cast<std::uint16_t>(v.result));w.i32(v.root_x);w.i32(v.root_y);w.u32(v.pointer_window);w.u32(v.focus_window);w.u16(v.state);w.u16(v.reserved16);w.u32(v.delivered_event_count);w.u32(v.flags);return std::move(w).take();}
CodecStatus decode(std::span<const std::uint8_t>b,SyntheticInputAcknowledged&v){ByteReader r(b);SyntheticInputAcknowledged x;std::uint16_t result;if(!r.u64(x.input_id)||!r.u32(x.time_ms)||!r.u16(result)||!r.i32(x.root_x)||!r.i32(x.root_y)||!r.u32(x.pointer_window)||!r.u32(x.focus_window)||!r.u16(x.state)||!r.u16(x.reserved16)||!r.u32(x.delivered_event_count)||!r.u32(x.flags))return CodecStatus::Truncated;if(!r.done())return CodecStatus::TrailingData;x.result=static_cast<SyntheticInputResult>(result);if(!x.input_id||!x.time_ms||result<1||result>6||x.reserved16||x.flags)return CodecStatus::InvalidValue;v=x;return CodecStatus::Ok;}
}
